=== sispi/servizi-scolastici/Sources/ks-lib-docer/services/conservazione/conservazione.batch/conservazione.batch.docerLib/src/main/resources/batchData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="batchData">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="callerApplication" type="xs:string" />
    			<xs:element name="mapping" type="mappingTypeStrict" minOccurs="1"/>
    			<xs:element name="search" type="searchType" maxOccurs="unbounded" />
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:complexType name="mappingTypeStrict">
    	<xs:sequence>
    		<xs:element name="documentType" type="xs:string" />
    		<xs:element name="callerApplication" type="xs:string" />
    		<xs:element name="tipoConservazione" type="xs:string" />
    		<xs:element name="forzaCollegamento" type="xs:string" />
    		<xs:element name="forzaAccettazione" type="xs:string" />
    		<xs:element name="forzaConservazione" type="xs:string" />
    		<xs:element name="dataRegistrazione" type="xs:string" minOccurs="0" />
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="mappingTypeLoose">
    	<xs:sequence>
    		<xs:element name="documentType" type="xs:string" minOccurs="0"/>
    		<xs:element name="callerApplication" type="xs:string" minOccurs="0" />
    		<xs:element name="tipoConservazione" type="xs:string" minOccurs="0" />
    		<xs:element name="forzaCollegamento" type="xs:string" minOccurs="0" />
    		<xs:element name="forzaAccettazione" type="xs:string" minOccurs="0" />
    		<xs:element name="forzaConservazione" type="xs:string" minOccurs="0" />
    		<xs:element name="dataRegistrazione" type="xs:string" minOccurs="0" />
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="searchType">
    	<xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
    		<xs:element name="documentType" type="xs:string" />
    		<xs:element name="tipoConservazione">
    			<xs:simpleType>
    				<xs:restriction base="xs:NMTOKEN">
    					<xs:enumeration value="SOSTITUTIVA" />
    					<xs:enumeration value="FISCALE" />
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="mapping" type="mappingTypeLoose" minOccurs="0" />
    		<xs:element name="criterias" type="criteriasType" />
			<xs:element name="identifierColumnNames" type="columnNamesType" />
    		<xs:element name="documentColumnNames" type="columnNamesType" />
    		<xs:element name="attachmentColumnNames" type="columnNamesType" />
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="criteriasType">
    	<xs:sequence>
    		<xs:element name="criteria" type="criteriaType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="criteriaType">
    	<xs:sequence>
    		<xs:element name="value" type="xs:string" maxOccurs="unbounded" />
    	</xs:sequence>
    	<xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="columnNamesType">
    	<xs:sequence>
    		<xs:element name="column" maxOccurs="unbounded" />
    	</xs:sequence>
    </xs:complexType>

</xs:schema>

=== sispi/servizi-scolastici/Sources/ks-lib-docer/services/conservazione/conservazione.batch/conservazione.batch.docerLib/src/test/resources/batchData.xml
<?xml version="1.0" encoding="utf-8"?>

<batchData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../main/resources/batchData.xsd">

	<callerApplication>docer-siir</callerApplication>

	<mapping>
		<documentType>TYPE_ID</documentType>
		<callerApplication>APP_VERSANTE</callerApplication>
		<tipoConservazione>T_CONSERV</tipoConservazione>
		<forzaCollegamento>FORZA_COLL</forzaCollegamento>
		<forzaAccettazione>FORZA_ACCETTAZ</forzaAccettazione>
		<forzaConservazione>FORZA_CONSERV</forzaConservazione>
	</mapping>

    <search>
        <description>TEST</description>
        <documentType>default</documentType>
        <tipoConservazione>SOSTITUTIVA</tipoConservazione>
        <criterias>
            <criteria name="COD_ENTE">
                <value>ENTEPROVA</value>
            </criteria>
            <criteria name="COD_AOO">
                <value>AOOPROVA</value>
            </criteria>
            <criteria name="STATO_CONSERV">
                <value>1</value>
            </criteria>
        </criterias>

        <identifierColumnNames>
            <column>TYPE_ID</column>
            <column>DOCNUM</column>
        </identifierColumnNames>

		<documentColumnNames>
            <!-- Colonne usate per il mapping -->
			<column>TYPE_ID</column>
            <column>APP_VERSANTE</column>
            <column>T_CONSERV</column>
            <column>FORZA_COLL</column>
            <column>FORZA_ACCETTAZ</column>
            <column>FORZA_CONSERV</column>
            <!-- Colonne di base comuni a tutti i TYPE_ID -->
            <column>DOCNAME</column>
            <column>DOCNUM</column>
            <column>COD_ENTE</column>
            <column>COD_AOO</column>
            <column>NUM_PG</column>
            <column>ANNO_PG</column>
            <column>PROGR_FASCICOLO</column>
            <column>ANNO_FASCICOLO</column>
            <column>CLASSIFICA</column>
            <column>FASC_SECONDARI</column>
            <column>OGGETTO_PG</column>
            <column>CREATION_DATE</column>
            <column>USA_D_CO_CER</column>
            <column>D_CO_CER</column>
            <column>T_D_CONTR_CER</column>
		</documentColumnNames>

		<attachmentColumnNames>
			<column>DOCNUM</column>
            <column>DOCNAME</column>
		</attachmentColumnNames>
    </search>
    
	<search>
        <description>DPG/DIB</description>

        <documentType>default</documentType>
		<tipoConservazione>SOSTITUTIVA</tipoConservazione>

		<criterias>
            <criteria name="COD_ENTE">
                <value>EMR</value>
            </criteria>
            <criteria name="COD_AOO">
                <value>AOO_EMR</value>
                <value>AOO_IB</value>
            </criteria>
			<criteria name="STATO_ARCHIVISTICO">
				<value>2</value>
				<value>3</value>
				<value>4</value>
				<value>5</value>
			</criteria>
			<criteria name="STATO_CONSERV">
				<value>1</value>
			</criteria>
            <criteria name="TIPO_COMPONENTE">
                <value>PRINCIPALE</value>
            </criteria>
            <!-- Atti del Dirigente -->
            <criteria name="TYPE_ID">
                <value>DPG</value>
                <value>DIB</value>
            </criteria>
		</criterias>

        <identifierColumnNames>
            <column>TYPE_ID</column>
            <column>DOCNUM</column>
        </identifierColumnNames>

		<documentColumnNames>
            <!-- Colonne usate per il mapping -->
			<column>TYPE_ID</column>
            <column>APP_VERSANTE</column>
            <column>T_CONSERV</column>
            <column>FORZA_COLL</column>
            <column>FORZA_ACCETTAZ</column>
            <column>FORZA_CONSERV</column>
            <!-- Colonne di base comuni a tutti i TYPE_ID -->
            <column>DOCNAME</column>
            <column>DOCNUM</column>
            <column>COD_ENTE</column>
            <column>COD_AOO</column>
            <column>NUM_PG</column>
            <column>ANNO_PG</column>
            <column>PROGR_FASCICOLO</column>
            <column>ANNO_FASCICOLO</column>
            <column>CLASSIFICA</column>
            <column>FASC_SECONDARI</column>
            <column>OGGETTO_PG</column>
            <column>CREATION_DATE</column>
            <column>USA_D_CO_CER</column>
            <column>D_CO_CER</column>
            <column>T_D_CONTR_CER</column>
            <!-- Metadati specifici -->
            <column>MS_T_REGISTRAZ</column>
            <column>MS_N_ADOZIONE_AM</column>
            <column>MS_D_ADOZIONE_AM</column>
            <column>MS_L_ADOZIONE_AM</column>
            <column>MS_FIRMATARIO</column>
            <column>MS_STRUTT_ADOTT</column>
            <column>MS_EPUB_BUR_AM</column>
            <column>MS_DPUB_BUR_AM</column>
            <column>MS_EPUB_SUBUR_AM</column>
            <column>MS_DPUB_SUBUR_AM</column>
            <column>MS_PROTREVATT_AM</column>
            <column>MS_D_REVOCA_AM</column>
		</documentColumnNames>

		<attachmentColumnNames>
			<column>DOCNUM</column>
            <column>DOCNAME</column>
		</attachmentColumnNames>

	</search>
    
    <search>
        <description>BURERT</description>

        <documentType>default</documentType>
        <tipoConservazione>SOSTITUTIVA</tipoConservazione>

        <criterias>
            <criteria name="COD_ENTE">
                <value>EMR</value>
            </criteria>
            <criteria name="COD_AOO">
                <value>AOO_EMR</value>
            </criteria>
            <criteria name="STATO_ARCHIVISTICO">
                <value>2</value>
                <value>3</value>
                <value>4</value>
                <value>5</value>
            </criteria>
            <criteria name="STATO_CONSERV">
                <value>1</value>
            </criteria>
            <criteria name="TIPO_COMPONENTE">
                <value>PRINCIPALE</value>
            </criteria>
            <!-- Bollettino Ufficiale -->
            <criteria name="TYPE_ID">
                <value>BURERT</value>
            </criteria>
        </criterias>

        <identifierColumnNames>
            <column>TYPE_ID</column>
            <column>DOCNUM</column>
        </identifierColumnNames>

        <documentColumnNames>
            <!-- Colonne usate per il mapping -->
            <column>TYPE_ID</column>
            <column>APP_VERSANTE</column>
            <column>T_CONSERV</column>
            <column>FORZA_COLL</column>
            <column>FORZA_ACCETTAZ</column>
            <column>FORZA_CONSERV</column>
            <!-- Colonne di base comuni a tutti i TYPE_ID -->
            <column>DOCNAME</column>
            <column>DOCNUM</column>
            <column>COD_ENTE</column>
            <column>COD_AOO</column>
            <column>NUM_PG</column>
            <column>ANNO_PG</column>
            <column>PROGR_FASCICOLO</column>
            <column>ANNO_FASCICOLO</column>
            <column>CLASSIFICA</column>
            <column>FASC_SECONDARI</column>
            <column>OGGETTO_PG</column>
            <column>CREATION_DATE</column>
            <column>USA_D_CO_CER</column>
            <column>D_CO_CER</column>
            <column>T_D_CONTR_CER</column>
            <!-- Metadati specifici -->
            <column>ANNATA_BU</column>
            <column>DATA_BU</column>
            <column>NUMERAZIONE_BU</column>
            <column>NUMERO_BU</column>
            <column>PARTE_BU</column>
        </documentColumnNames>

        <attachmentColumnNames>
            <column>DOCNUM</column>
            <column>DOCNAME</column>
        </attachmentColumnNames>

    </search>
    
    <search>

        <description>NP</description>

        <documentType>default</documentType>
        <tipoConservazione>SOSTITUTIVA</tipoConservazione>

        <criterias>
            <criteria name="COD_ENTE">
                <value>EMR</value>
            </criteria>
            <criteria name="COD_AOO">
                <value>AOO_EMR</value>
                <value>AOO_IB</value>                
            </criteria>
            <criteria name="STATO_ARCHIVISTICO">
                <value>2</value>
                <value>3</value>
                <value>4</value>
                <value>5</value>
            </criteria>
            <criteria name="STATO_CONSERV">
                <value>1</value>
            </criteria>
            <criteria name="TIPO_COMPONENTE">
                <value>PRINCIPALE</value>
            </criteria>
            <!-- Non protocollato -->
            <criteria name="TYPE_ID">
                <value>NP</value>
            </criteria>
        </criterias>

        <identifierColumnNames>
            <column>TYPE_ID</column>
            <column>DOCNUM</column>
        </identifierColumnNames>

        <documentColumnNames>
            <!-- Colonne usate per il mapping -->
            <column>TYPE_ID</column>
            <column>APP_VERSANTE</column>
            <column>T_CONSERV</column>
            <column>FORZA_COLL</column>
            <column>FORZA_ACCETTAZ</column>
            <column>FORZA_CONSERV</column>
            <!-- Colonne di base comuni a tutti i TYPE_ID -->
            <column>DOCNAME</column>
            <column>DOCNUM</column>
            <column>COD_ENTE</column>
            <column>COD_AOO</column>
            <column>NUM_PG</column>
            <column>ANNO_PG</column>
            <column>PROGR_FASCICOLO</column>
            <column>ANNO_FASCICOLO</column>
            <column>CLASSIFICA</column>
            <column>FASC_SECONDARI</column>
            <column>OGGETTO_PG</column>
            <column>CREATION_DATE</column>
            <column>USA_D_CO_CER</column>
            <column>D_CO_CER</column>
            <column>T_D_CONTR_CER</column>
            <!-- Metadati specifici -->
            <column>MS_T_REGISTRAZ</column>
        </documentColumnNames>

        <attachmentColumnNames>
            <column>DOCNUM</column>
            <column>DOCNAME</column>
