=== sispi/servizi-scolastici/Sources/ks-lib-docer/services/conservazione/conservazione.webservice/src/test/resources/WSVersamentoRequest.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Hand written on 2011 by Francesco Fioravanti -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wmh="http://www.wmhelp.com/2003/eGenerator" elementFormDefault="qualified">
  <!--  -->
  <xs:complexType name="IntestazioneType">
    <xs:sequence>
      <xs:element name="Versatore" type="VersatoreType"/>
      <xs:element name="Chiave" type="ChiaveType"/>
      <xs:element name="TipologiaUnitaDocumentaria" type="xs:token"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType  name="VersatoreType">
    <xs:sequence>
      <xs:element name="Ambiente" type="xs:token"/>
      <xs:element name="Ente" type="xs:token"/>
      <xs:element name="Struttura" type="xs:token"/>
      <xs:element name="UserID" type="xs:token"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="ChiaveType">
    <xs:sequence>
      <xs:element name="Numero" type="xs:token"/>
      <xs:element name="Anno" type="xs:nonNegativeInteger"/>
      <xs:element name="TipoRegistro" type="xs:token"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  
  <!--  -->
  <xs:complexType name="ConfigType">
    <xs:sequence>
      <xs:element name="TipoConservazione" type="TipoConservazioneType" maxOccurs="1" minOccurs="0"/>
      <xs:element name="ForzaAccetazione" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
      <xs:element name="ForzaConservazione" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
      <xs:element name="ForzaCollegamento" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:simpleType name="TipoConservazioneType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="SOSTITUTIVA"/>
      <xs:enumeration value="FISCALE"/>
    </xs:restriction>
  </xs:simpleType>
  <!--  -->
  <xs:complexType name="ProfiloArchivisticoType">
    <xs:sequence>
      <xs:element name="FascicoloPrincipale" type="CamiciaFascicoloType"/>
      <xs:element name="FascicoliSecondari"  maxOccurs="1" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="FascicoloSecondario" type="CamiciaFascicoloType" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="CamiciaFascicoloType">
    <xs:sequence>
      <xs:element name="Classifica" type="xs:token" maxOccurs="1" minOccurs="0"/>
      <xs:element name="Fascicolo" type="FascicoloType" maxOccurs="1" minOccurs="0"/>
      <xs:element name="SottoFascicolo" type="FascicoloType" maxOccurs="1" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="FascicoloType">
    <xs:sequence>
      <xs:element name="Identificativo"  type="xs:token" />
      <xs:element name="Oggetto" type="xs:string"  nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="ProfiloUnitaDocumentariaType">
    <xs:sequence>
      <xs:element name="Oggetto" type="xs:string"/>
      <xs:element name="Data" type="xs:date"/>
      <xs:element name="Cartaceo" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="DocumentoCollegatoType">
    <xs:sequence>
      <xs:element name="DocumentoCollegato"  minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ChiaveCollegamento" type="ChiaveType"/>
            <xs:element name="DescrizioneCollegamento" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!--  -->


  <!--  -->
  <xs:complexType name="DocumentoType">
    <xs:sequence>
      <xs:element name="IDDocumento" type="xs:token"/>
      <xs:element name="TipoDocumento" type="xs:token"/>
      <xs:element name="ProfiloDocumento" type="ProfiloDocumentoType" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="DatiSpecifici" maxOccurs="1" minOccurs="0" nillable="true">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="VersioneDatiSpecifici" type="xs:token"/>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DatiFiscali" type="DatiFiscaliType" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="StrutturaOriginale" type="StrutturaType"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="ProfiloDocumentoType">
    <xs:sequence>
      <xs:element name="Descrizione" type="xs:string" maxOccurs="1" minOccurs="0"/>
      <xs:element name="Autore" type="xs:string" maxOccurs="1" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="DatiFiscaliType">
    <xs:sequence>
      <xs:element name="Denominazione" type="xs:string"  maxOccurs="1" minOccurs="0"/>
      <xs:element name="Nome" type="xs:string"  maxOccurs="1" minOccurs="0"/>
      <xs:element name="Cognome" type="xs:string"  maxOccurs="1" minOccurs="0"/>
      <xs:element name="CF" maxOccurs="1" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:length value="16"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PIVA" maxOccurs="1" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:length value="11"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="DataEmissione" type="xs:date"/>
      <xs:element name="NumeroProgressivo" type="xs:positiveInteger"/>
      <xs:element name="Registro" type="xs:string"/>
      <xs:element name="PeriodoFiscale" type="xs:string"/>
      <xs:element name="DataTermineEmissione" type="xs:date"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="StrutturaType">
    <xs:sequence>
      <xs:element name="TipoStruttura" type="xs:token"/>
      <xs:element name="Componenti">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Componente" type="ComponenteType" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="ComponenteType">
    <xs:sequence>
      <xs:element name="ID" type="xs:token"/>
      <xs:element name="OrdinePresentazione" type="xs:nonNegativeInteger"/>
      <xs:element name="TipoComponente" type="xs:token"/>
      <xs:element name="TipoSupportoComponente" type="TipoSupportoType"/>
      <xs:element name="Riferimento" type="ChiaveType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="TipoRappresentazioneComponente" type="xs:token" minOccurs="0" maxOccurs="1"/>
      <xs:element name="NomeComponente" type="xs:token" minOccurs="0" maxOccurs="1"/>
      <xs:element name="FormatoFileVersato" type="xs:token"  minOccurs="0" maxOccurs="1"/>
      <xs:element name="HashVersato" type="xs:hexBinary" minOccurs="0" maxOccurs="1"/>
      <xs:element name="UrnVersato" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
      <xs:element name="IDComponenteVersato" type="xs:token" minOccurs="0" maxOccurs="1"/>
      <xs:element name="UtilizzoDataFirmaPerRifTemp" type="xs:boolean"/>
      <xs:element name="RiferimentoTemporale" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
      <xs:element name="DescrizioneRiferimentoTemporale" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="SottoComponenti" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="SottoComponente" type="SottoComponenteType"  minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:complexType name="SottoComponenteType">
    <xs:sequence>
      <xs:element name="ID" type="xs:token"/>
      <xs:element name="OrdinePresentazione" type="xs:nonNegativeInteger"/>
      <xs:element name="TipoComponente" type="xs:token"/>
      <xs:element name="TipoSupportoComponente" type="TipoSupportoType"/>
      <xs:element name="Riferimento" type="ChiaveType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="NomeComponente" type="xs:token" minOccurs="0" maxOccurs="1"/>
      <xs:element name="FormatoFileVersato" type="xs:token"  minOccurs="0" maxOccurs="1"/>
      <xs:element name="UrnVersato" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
      <xs:element name="IDComponenteVersato" type="xs:token" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <!--  -->
  <xs:simpleType name="TipoSupportoType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="FILE"/>
      <xs:enumeration value="METADATI"/>
    </xs:restriction>
  </xs:simpleType>
  <!--  -->
  <!--  -->
  <!--  -->
  <xs:element name="UnitaDocumentaria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Intestazione" type="IntestazioneType"  maxOccurs="1" minOccurs="1" />
        <xs:element name="Configurazione" type="ConfigType" maxOccurs="1" minOccurs="0"/>
        <xs:element name="ProfiloArchivistico" type="ProfiloArchivisticoType" maxOccurs="1" minOccurs="0"/>
        <xs:element name="ProfiloUnitaDocumentaria" type="ProfiloUnitaDocumentariaType" maxOccurs="1" minOccurs="0"/>
        <xs:element name="DocumentiCollegati" type="DocumentoCollegatoType" maxOccurs="1" minOccurs="0"/>
        <!--  -->
        <xs:element name="NumeroAllegati" type="xs:nonNegativeInteger" maxOccurs="1" minOccurs="0"/>
        <xs:element name="NumeroAnnessi" type="xs:nonNegativeInteger" maxOccurs="1" minOccurs="0"/>
        <xs:element name="NumeroAnnotazioni" type="xs:nonNegativeInteger" maxOccurs="1" minOccurs="0"/>
        <!--  -->
        <xs:element name="DocumentoPrincipale" type="DocumentoType" maxOccurs="1" minOccurs="1"/>
        <xs:element name="Allegati" maxOccurs="1" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Allegato" type="DocumentoType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Annessi" maxOccurs="1" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Annesso" type="DocumentoType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Annotazioni" maxOccurs="1" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Annotazione" type="DocumentoType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--  -->
</xs:schema>

=== sispi/servizi-scolastici/Sources/ks-lib-docer/services/conservazione/conservazione.webservice/src/test/resources/mixed-minimal.xml
<?xml version="1.0" encoding="utf-8"?>

<UnitaDocumentaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="WSVersamentoRequest.xsd">
	<Intestazione>
		<Versatore>
			<Ambiente>abc</Ambiente>
			<Ente>abc</Ente>
			<Struttura>abc</Struttura>
			<UserID>abc</UserID>
		</Versatore>
		<Chiave>
			<Numero>12</Numero>
			<Anno>2000</Anno>
			<TipoRegistro>REGISTRO</TipoRegistro>			
		</Chiave>
		<TipologiaUnitaDocumentaria>asd</TipologiaUnitaDocumentaria>
	</Intestazione>
	<Configurazione>
		<TipoConservazione>SOSTITUTIVA</TipoConservazione>	
		<ForzaAccetazione>true</ForzaAccetazione>
		<ForzaConservazione>true</ForzaConservazione>
		<ForzaCollegamento>true</ForzaCollegamento>
	</Configurazione>
	<ProfiloArchivistico>
		<FascicoloPrincipale>
			<Fascicolo>
				<Identificativo>123</Identificativo>
				<Oggetto>asd</Oggetto>
			</Fascicolo>
		</FascicoloPrincipale>
		<FascicoliSecondari>
			<FascicoloSecondario>
				<Fascicolo>
					<Identificativo>123</Identificativo>
					<Oggetto>asd</Oggetto>
				</Fascicolo>
				<SottoFascicolo>
					<Identificativo>123</Identificativo>
					<Oggetto>asd</Oggetto>
				</SottoFascicolo>
			</FascicoloSecondario>
			<FascicoloSecondario>
				<Classifica>1</Classifica>
			</FascicoloSecondario>
			<FascicoloSecondario />
		</FascicoliSecondari>
	</ProfiloArchivistico>
	<ProfiloUnitaDocumentaria>
		<Oggetto>abc</Oggetto>
		<Data>2011-10-10</Data>
	</ProfiloUnitaDocumentaria>
	<DocumentiCollegati>
		<DocumentoCollegato>
			<ChiaveCollegamento>
				<Numero>123</Numero>
				<Anno>1234</Anno>
				<TipoRegistro>REGISTRO</TipoRegistro>
			</ChiaveCollegamento>
			<DescrizioneCollegamento>asd</DescrizioneCollegamento>
		</DocumentoCollegato>
	</DocumentiCollegati>
	<NumeroAllegati>0</NumeroAllegati>
	<NumeroAnnessi>0</NumeroAnnessi>
	<NumeroAnnotazioni>0</NumeroAnnotazioni>
	<DocumentoPrincipale>
		<IDDocumento>123</IDDocumento>
		<TipoDocumento>FILE</TipoDocumento>
		<ProfiloDocumento></ProfiloDocumento>
		<DatiFiscali>
			<DataEmissione>2010-10-10</DataEmissione>
			<NumeroProgressivo>123</NumeroProgressivo>
			<Registro>REGISTRO</Registro>
			<PeriodoFiscale>periodo</PeriodoFiscale>
			<DataTermineEmissione>2011-11-11</DataTermineEmissione>
		</DatiFiscali>
		<StrutturaOriginale>
			<TipoStruttura>STRUTTURA</TipoStruttura>
			<Componenti>
				<Componente>
					<ID>123</ID>
					<OrdinePresentazione>1</OrdinePresentazione>
					<TipoComponente>FILE</TipoComponente>
					<TipoSupportoComponente>FILE</TipoSupportoComponente>
					<UtilizzoDataFirmaPerRifTemp>false</UtilizzoDataFirmaPerRifTemp>
				</Componente>
			</Componenti>
		</StrutturaOriginale>
	</DocumentoPrincipale>
</UnitaDocumentaria>

=== sispi/servizi-scolastici/Sources/ks-lib-docer/services/conservazione/conservazione.webservice/src/test/resources/full.xml
<?xml version="1.0" encoding="utf-8"?>

<UnitaDocumentaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="WSVersamentoRequest.xsd">

	<Intestazione>
		<Versatore>
			<Ambiente>COMUNI</Ambiente>
			<Ente>COMUNE_PARMA</Ente>
			<Struttura>AOO000</Struttura>
			<UserID>admin</UserID>
		</Versatore>
		<Chiave>
			<Numero>5</Numero>
			<Anno>2011</Anno>
			<TipoRegistro>PG</TipoRegistro>
		</Chiave>
		<TipologiaUnitaDocumentaria>PROTOCOLLO</TipologiaUnitaDocumentaria>
	</Intestazione>
	<Configurazione>
		<TipoConservazione>SOSTITUTIVA</TipoConservazione>
		<ForzaAccetazione>true</ForzaAccetazione>
		<ForzaConservazione>true</ForzaConservazione>
		<ForzaCollegamento>true</ForzaCollegamento>
	</Configurazione>
	<ProfiloArchivistico>
		<FascicoloPrincipale>
			<Classifica>1.0.0</Classifica>
			<Fascicolo>
				<Identificativo>1.0.0/2011/1</Identificativo>
				<Oggetto>Pratica XXX</Oggetto>
			</Fascicolo>
			<SottoFascicolo>
				<Identificativo>1.0.0/2011/1/1</Identificativo>
				<Oggetto>Giustificativi</Oggetto>
			</SottoFascicolo>
		</FascicoloPrincipale>
		<FascicoliSecondari>
			<FascicoloSecondario>
				<Classifica>2.0</Classifica>
				<Fascicolo>
					<Identificativo>2.0/2011/2</Identificativo>
					<Oggetto>Acquisti Vari</Oggetto>
				</Fascicolo>
			</FascicoloSecondario>
			<FascicoloSecondario>
				<Classifica>2.1</Classifica>
				<Fascicolo>
					<Identificativo>2.1/2011/3</Identificativo>
					<Oggetto>Oggetto del fascicolo 2.1</Oggetto>
				</Fascicolo>
				<SottoFascicolo>
					<Identificativo>2.1/2011/3/1</Identificativo>
					<Oggetto>Prova</Oggetto>
				</SottoFascicolo>
			</FascicoloSecondario>
		</FascicoliSecondari>
	</ProfiloArchivistico>
	<ProfiloUnitaDocumentaria>
		<Oggetto>Domanda di permesso di costruire presentata da Paola Righi
			(RGHPLA74P65H827X) nata a Milano il 25/09/1974 residente in Parma via
			XX 8</Oggetto>
		<Data>2011-01-01</Data>
		<Cartaceo>true</Cartaceo>
	</ProfiloUnitaDocumentaria>
	<DocumentiCollegati>
		<DocumentoCollegato>
			<ChiaveCollegamento>
				<Numero>12</Numero>
				<Anno>1234</Anno>
				<TipoRegistro>asd</TipoRegistro>
			</ChiaveCollegamento>
			<DescrizioneCollegamento>string</DescrizioneCollegamento>
		</DocumentoCollegato>
	</DocumentiCollegati>
	<NumeroAllegati>1</NumeroAllegati>
	<NumeroAnnessi>1</NumeroAnnessi>
	<NumeroAnnotazioni>1</NumeroAnnotazioni>

	<DocumentoPrincipale>
		<IDDocumento>015</IDDocumento>
		<TipoDocumento>RICHIESTA_PERMESSO_EDILIZIO</TipoDocumento>
		<ProfiloDocumento>
			<Descrizione>Istanza del Richiedente</Descrizione>
			<Autore>Paolo Rossi</Autore>
		</ProfiloDocumento>
		<DatiSpecifici>
			<VersioneDatiSpecifici>1.0</VersioneDatiSpecifici>
			<DenominazioneDirettoreLavori>Giuseppe Bianchi</DenominazioneDirettoreLavori>
			<CFDirettoreLavori>BNCGSP54G18H140V</CFDirettoreLavori>
			<DenominazioneImpresaEsecutriceOpere>Rossi &amp; C.</DenominazioneImpresaEsecutriceOpere>
			<PIVAImpresaEsecutriceOpere>11122456124</PIVAImpresaEsecutriceOpere>
		</DatiSpecifici>
		<DatiFiscali>
			<Denominazione>string</Denominazione>
			<Nome>string</Nome>
			<Cognome>string</Cognome>
			<CF>1234567890abcdef</CF>
			<PIVA>1234567890a</PIVA>
			<DataEmissione>1973-04-04</DataEmissione>
			<NumeroProgressivo>12</NumeroProgressivo>
			<Registro>0</Registro>
			<PeriodoFiscale>string</PeriodoFiscale>
			<DataTermineEmissione>1973-04-04</DataTermineEmissione>
		</DatiFiscali>
		<StrutturaOriginale>
			<TipoStruttura>TESTO_FIRMA_DETACHED</TipoStruttura>
			<Componenti>
				<Componente>
					<ID>1</ID>
					<OrdinePresentazione>1</OrdinePresentazione>
					<TipoComponente>CONTENUTO</TipoComponente>
					<TipoSupportoComponente>FILE</TipoSupportoComponente>
					<Riferimento>
						<Numero>123</Numero>
						<Anno>1234</Anno>
						<TipoRegistro>REGISTRO</TipoRegistro>
					</Riferimento>
					<TipoRappresentazioneComponente />
					<NomeComponente>DomandaPermessoRighi.pdf</NomeComponente>
					<FormatoFileVersato>PDF</FormatoFileVersato>
					<HashVersato>12345abcde</HashVersato>
					<UrnVersato>c:\cartella permessi\righi.pdf.p7m</UrnVersato>
					<IDComponenteVersato>0014</IDComponenteVersato>
					<UtilizzoDataFirmaPerRifTemp>true</UtilizzoDataFirmaPerRifTemp>
					<RiferimentoTemporale>2010-11-11T10:10:00.000</RiferimentoTemporale>
					<DescrizioneRiferimentoTemporale />
					<SottoComponenti>
						<SottoComponente>
							<ID>2</ID>
							<OrdinePresentazione>2</OrdinePresentazione>
							<TipoComponente>FIRMA</TipoComponente>
							<TipoSupportoComponente>FILE</TipoSupportoComponente>
							<NomeComponente>DomandaPermessoRighi.pdf.p7m</NomeComponente>
							<FormatoFileVersato>p7m</FormatoFileVersato>
							<UrnVersato />
							<IDComponenteVersato />
						</SottoComponente>
					</SottoComponenti>
				</Componente>
			</Componenti>
		</StrutturaOriginale>
	</DocumentoPrincipale>
	<Allegati>
		<Allegato>
			<IDDocumento>018</IDDocumento>
			<TipoDocumento>GENERICO</TipoDocumento>
			<ProfiloDocumento>
				<Descrizione>Ricevuta Versamento relativa ai diritti di segreteria
				</Descrizione>
				<Autore />
			</ProfiloDocumento>
			<StrutturaOriginale>
				<TipoStruttura>TESTO</TipoStruttura>
				<Componenti>
					<Componente>
						<ID>3</ID>
						<OrdinePresentazione>1</OrdinePresentazione>
						<TipoComponente>CONTENUTO</TipoComponente>
						<TipoSupportoComponente>FILE</TipoSupportoComponente>
						<TipoRappresentazioneComponente />
						<NomeComponente>ricevutaversamentorighi.tiff</NomeComponente>
						<FormatoFileVersato>TIFF</FormatoFileVersato>
						<HashVersato />
						<UrnVersato />
						<IDComponenteVersato />
						<UtilizzoDataFirmaPerRifTemp>false</UtilizzoDataFirmaPerRifTemp>
						<DescrizioneRiferimentoTemporale />
					</Componente>
				</Componenti>
			</StrutturaOriginale>
		</Allegato>
	</Allegati>
	<Annessi>
		<Annesso>
			<IDDocumento>019</IDDocumento>
			<TipoDocumento>GENERICO</TipoDocumento>
			<ProfiloDocumento>
				<Descrizione>Parere di Conformit√†</Descrizione>
				<Autore />
			</ProfiloDocumento>
			<StrutturaOriginale>
				<TipoStruttura>TESTO_FIRMA_EMBEDDED</TipoStruttura>
				<Componenti>
					<Componente>
						<ID>4</ID>
						<OrdinePresentazione>1</OrdinePresentazione>
						<TipoComponente>CONTENUTO</TipoComponente>
						<TipoSupportoComponente>FILE</TipoSupportoComponente>
						<TipoRappresentazioneComponente />
						<NomeComponente>parere.pdf.p7m</NomeComponente>
						<FormatoFileVersato>p7m</FormatoFileVersato>
						<HashVersato>12345abcde</HashVersato>
						<UrnVersato />
						<IDComponenteVersato>0236</IDComponenteVersato>
						<UtilizzoDataFirmaPerRifTemp>false</UtilizzoDataFirmaPerRifTemp>
						<RiferimentoTemporale>2000-03-11T09:00:00.000</RiferimentoTemporale>
						<DescrizioneRiferimentoTemporale>Riferimento temporale versato</DescrizioneRiferimentoTemporale>
					</Componente>
				</Componenti>
			</StrutturaOriginale>
		</Annesso>
	</Annessi>
	<Annotazioni>
		<Annotazione>
			<IDDocumento>025</IDDocumento>
			<TipoDocumento>GENERICO</TipoDocumento>
			<ProfiloDocumento>
				<Descrizione>segnatura di protocollo</Descrizione>
				<Autore />
			</ProfiloDocumento>
			<StrutturaOriginale>
				<TipoStruttura>XML</TipoStruttura>
				<Componenti>
					<Componente>
						<ID>token</ID>
						<OrdinePresentazione>0</OrdinePresentazione>
						<TipoComponente>SEGNATURA</TipoComponente>
						<TipoSupportoComponente>FILE</TipoSupportoComponente>
						<TipoRappresentazioneComponente />
						<NomeComponente>segnatura.xml</NomeComponente>
						<FormatoFileVersato>XML</FormatoFileVersato>
						<HashVersato>12345abcde</HashVersato>
						<UrnVersato />
						<IDComponenteVersato />
						<UtilizzoDataFirmaPerRifTemp>false</UtilizzoDataFirmaPerRifTemp>
						<DescrizioneRiferimentoTemporale />
					</Componente>
				</Componenti>
			</StrutturaOriginale>
		</Annotazione>
	</Annotazioni>
</UnitaDocumentaria>
